### ISSUE TITLE
This gem is unavailable on rubygems.com

### ISSUE THREAD

**Issue by andreibondarev** [serpapi/serpapi-ruby#3]
When are you planning on publishing this gem on Rubygems?

**Comment by hartator** [comment]
This is just for internal testing for now. Soon™.

We have another Ruby lib here: https://github.com/serpapi/google-search-results-ruby

**Comment by ibrahima** [comment]
Ahh, so this is not the official client library that we should use? It might be helpful to specify this in the README. I think I found this via a google search and got confused about the difference between this gem and that one.

**Comment by hilmanski** [comment]
Yes, correct. We apologize for the confusion and thank you very much for your feedback, @ibrahima. We'll let you know once we turn this into the official library for Ruby.

If you have any other questions or concerns, please contact us at contact@serpapi.com

**Comment by hilmanski** [comment]
We've added the disclaimer to the readme file. Thank you very much for the suggestion @ibrahima!

https://github.com/serpapi/serpapi-ruby?tab=readme-ov-file
